/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author USUARIO
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnProfesor = new javax.swing.JButton();
        BtnCurso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnEstudiante = new javax.swing.JButton();
        BtnMatricular = new javax.swing.JButton();
        BtnAsignarCursos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnProfesor.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        BtnProfesor.setText("Agregar profesor");
        BtnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfesorActionPerformed(evt);
            }
        });

        BtnCurso.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/online-learning.png"))); // NOI18N
        BtnCurso.setText("Agregar Cursos");
        BtnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCursoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        BtnEstudiante.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        BtnEstudiante.setText("Agregar estudiante");
        BtnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEstudianteActionPerformed(evt);
            }
        });

        BtnMatricular.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/online-learning.png"))); // NOI18N
        BtnMatricular.setText("Matricular");
        BtnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMatricularActionPerformed(evt);
            }
        });

        BtnAsignarCursos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        BtnAsignarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/online-learning.png"))); // NOI18N
        BtnAsignarCursos.setText("Asignar cursos");
        BtnAsignarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAsignarCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAsignarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnMatricular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(BtnProfesor)
                .addGap(18, 18, 18)
                .addComponent(BtnEstudiante)
                .addGap(18, 18, 18)
                .addComponent(BtnCurso)
                .addGap(18, 18, 18)
                .addComponent(BtnMatricular)
                .addGap(18, 18, 18)
                .addComponent(BtnAsignarCursos)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfesorActionPerformed
       FrmProfesores newframe = new FrmProfesores();
       newframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnProfesorActionPerformed

    private void BtnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCursoActionPerformed
       FrmCursos newframe = new  FrmCursos ();
       newframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnCursoActionPerformed

    private void BtnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMatricularActionPerformed
        FrmMatricula newframe =new FrmMatricula();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMatricularActionPerformed

    private void BtnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEstudianteActionPerformed
        FrmEstudiantes newframe = new FrmEstudiantes();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnEstudianteActionPerformed

    private void BtnAsignarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAsignarCursosActionPerformed
       FrmAsignarCurso newframe = new  FrmAsignarCurso();
       newframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnAsignarCursosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAsignarCursos;
    private javax.swing.JButton BtnCurso;
    private javax.swing.JButton BtnEstudiante;
    private javax.swing.JButton BtnMatricular;
    private javax.swing.JButton BtnProfesor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
