/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.ControllerEstudiante;
import Controller.ControllerCurso;
import Modell.ClaseCurso;
import Modell.ClaseEstudiante;
import Modell.ClaseProfesor;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static view.FrmCursosDictados.cursos;

/**
 *
 * @author Ambiente 209-2
 */
public class FrmMatricula extends javax.swing.JFrame {
 List<ClaseEstudiante> listaEstudiantes=ControllerEstudiante.getListaEstudiantes();
  private static List<ClaseCurso> cursos=ControllerCurso.getCursos();
  private Set<String> setDatos = new HashSet<String>();
  private boolean seAgregaronDatos = false;
    /**
     * Creates new form FrmMatricla
     */
    public FrmMatricula() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        BoxCursos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnMatricular = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        JlNombre = new javax.swing.JLabel();
        JlCodigo = new javax.swing.JLabel();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        JlCurso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoxCursos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BoxCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar" }));
        BoxCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxCursosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Matriculas");

        BtnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Estudia:");

        TxtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdentificacionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("identificación");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        BtnMatricular.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnMatricular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/online-learning.png"))); // NOI18N
        BtnMatricular.setText("matricular");
        BtnMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMatricularActionPerformed(evt);
            }
        });

        BtnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        BtnBuscar.setText("buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Cursos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(TxtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(BtnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(BoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnVolver)
                                            .addComponent(jLabel5))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(57, 57, 57)
                                        .addComponent(JlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnActualizar)
                .addGap(18, 18, 18)
                .addComponent(BtnMatricular)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BtnBuscar)
                    .addComponent(TxtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnActualizar)
                    .addComponent(BtnMatricular)
                    .addComponent(BtnVolver))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        FrmMenu newframe =  new FrmMenu();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BoxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxCursosActionPerformed
        comboBox();
    }//GEN-LAST:event_BoxCursosActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
         comboBox();
        for(ClaseEstudiante estudiant:listaEstudiantes){    // se recorre la lista    
        if(estudiant.getIdentificacion().equalsIgnoreCase(TxtIdentificacion.getText())){ // se mira la identificacion existe 
       JlNombre.setText(estudiant.getNombre()+" "+estudiant.getApellido());// se muestran los datos se la persona 
       JlCurso.setText(estudiant.getCurso()); // si tiene un curso se muestra 
        }
    }
  
        
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMatricularActionPerformed
      if (TxtIdentificacion.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "Campos obligatorios");
         }else{
          String nombre = (String) BoxCursos.getSelectedItem();
          if(nombre.equals("seleccionar")){
          JOptionPane.showMessageDialog(null, "por favor seleccione un curso");
          }
          ControllerEstudiante estudiante=new ControllerEstudiante();// se crea un objecto controlador 
          int codigo=Integer.parseInt(JlCodigo.getText());// se toma el codigo 
       
      
         for(ClaseEstudiante estudiant:listaEstudiantes){  //se recorre la lista de estudiantes      
         if(estudiant.getIdentificacion().equalsIgnoreCase(TxtIdentificacion.getText())){ // se verifica si esta 
            if (estudiante.matricular(codigo, estudiant)) {// se usa el metodo para matriclar
                
                JOptionPane.showMessageDialog(null, "matricula exitosa");// se muestra el mensaje y se busca 
                BtnBuscar.doClick();
            }else{
                 JOptionPane.showMessageDialog(null, "matricula  sin exitosa");
            }
        }
    }
      
    }//GEN-LAST:event_BtnMatricularActionPerformed
    }
    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
       ControllerEstudiante estudiante=new ControllerEstudiante();// se hace lo mismo que en agregar solo cambia le metood 
      int codigo=Integer.parseInt(JlCodigo.getText());
       
      
         for(ClaseEstudiante estudiant:listaEstudiantes){       
        if(estudiant.getIdentificacion().equalsIgnoreCase(TxtIdentificacion.getText())){ 
            if (estudiante.editarMatricula(codigo, estudiant)) {
                
                JOptionPane.showMessageDialog(null, "cambio exitoso");
                BtnBuscar.doClick();
            }else{
                 JOptionPane.showMessageDialog(null, "cambio no exitoso");
            }
        }
    } 
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        ControllerEstudiante estudiante=new ControllerEstudiante();
      int codigo=Integer.parseInt(JlCodigo.getText());// se hace lo mismo que en agregar perso cambia el metodo 
       
      
         for(ClaseEstudiante estudiant:listaEstudiantes){       
        if(estudiant.getIdentificacion().equalsIgnoreCase(TxtIdentificacion.getText())){ 
            if (estudiante.eliminarMatricula(codigo, estudiant)) {// aca cambia le metodo 
                
                JOptionPane.showMessageDialog(null, "eliminado  exitosamente");
                BtnBuscar.doClick();
            }else{
                 JOptionPane.showMessageDialog(null, "no eliminado");
            }
        }
    } 
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void TxtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdentificacionKeyTyped
        int key = evt.getKeyChar();
        
        boolean numeros = key >=48 && key <=57;
        
        if (!numeros){
          evt.consume();
         }
        if (TxtIdentificacion.getText().length()>=10){
          evt.consume();
        }
    }//GEN-LAST:event_TxtIdentificacionKeyTyped
      public void comboBox(){
                 if (!seAgregaronDatos) { // Verifica si ya se han agregado los datos y se hace lo mismo qu een el combo box de FrmCursosDisctados
       ControllerCurso otraClase = new ControllerCurso();
        Set<String> nombresCursosSinDuplicados = otraClase.getNombresCursosSinDuplicados();

        for (String nombre : nombresCursosSinDuplicados) {
            BoxCursos.addItem(nombre);
        }

        seAgregaronDatos = true;
    }
        String nombre = (String) BoxCursos.getSelectedItem();
    for (ClaseCurso curso : cursos) {
        if (nombre.equalsIgnoreCase(curso.getNombre())) {
            String codigo = Integer.toString(curso.getCodigo());
            JlCodigo.setText(codigo);
        }
    }
    
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCursos;
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnMatricular;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel JlCodigo;
    private javax.swing.JLabel JlCurso;
    private javax.swing.JLabel JlNombre;
    private javax.swing.JTextField TxtIdentificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
